#!/usr/bin/env sh

#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#sudo yabai --load-sa


# S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change &> /dev/null"

# Global Settings
	yabai -m config                                 \
    	layout                      bsp         	\
		auto_balance                on				\
    	top_padding                 10             	\
    	bottom_padding              10            	\
    	left_padding                10            	\
    	right_padding               10              \
    	window_gap                  10              \
	    mouse_drop_action 	       	swap			\
    	focus_follows_mouse 	   	autofocus		\
		mouse_follows_focus			on        		\
        window_shadow              	float           \
        window_opacity             	off             \
        window_opacity_duration    	0.2             \
        active_window_opacity      	1.0             \
        normal_window_opacity      	0.98            \
        insert_feedback_color      	0xff9dd274      \

# 64 left for vertical sketchy
# 44 top for top sketchybar

# Disable specific apps
yabai -m rule --add label="sys" app="^System.*einstellungen$"   					manage=off
yabai -m rule --add app="^iTerm"													manage=off mouse_follows_focus=on
yabai -m rule --add app="^Lunar$" title="^Settings"									manage=off
yabai -m rule --add app="^Grila$"               									manage=off
yabai -m rule --add app="^BusyCal$" title!="^$"										manage=off
yabai -m rule --add app="^Spark$" title!="^Spark - INBOX$"							manage=off
yabai -m rule --add app="^Shottr$" title="^Preferences$"							manage=off
yabai -m rule --add app="^Arc$" title="^Lukas$"				  						manage=off
yabai -m rule --add app="^Find Any File$" title="^Find Any File$"					manage=off
yabai -m rule --add app="^Finder$" title="^Papierkorb$|Kopieren$"					manage=off
yabai -m rule --add app="^BetterTouchTool$" title="^BetterTouchTool Settings$" 		manage=off
yabai -m rule --add app="^SigmaOS$" title!="^SigmaOS$"								manage=off
yabai -m rule --add app="^CleanShot X$"	title!="^(General|Annotate)$"				manage=on mouse_follows_focus=on
yabai -m rule --add app="^(Sideloadly!|Messages|MacUpdater|Alfred Preferences|Transmission|Little Snitch|ProtonVPN|IINA|Pixea|AltTab|WinDiskWriter|AppCleaner|Secrets|Bartender 5|DaisyDisk|Warnwetter|Keka|MediaMate|Rechner|App Store|Time Machine|Finder)$" manage=off mouse_follows_focus=on



echo "yabai configuration loaded.."



# OLD:

#		external_bar 					all:50:0

# Automatically float non-resizable windows, such as palettes, system settings etc.
#yabai -m signal --add event=window_created action="~/.config/yabai/float_small_windows.sh"



#
#   	mouse_modifier               	fn		            \
#	    mouse_action1                	move               	\
#  	    mouse_action2                	resize           	\
#       auto balance 					off     		\
#    	split_ratio                  	0.50          	\ 		\
#    	split_type                   	auto 			\
