#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	active_color="gradient(top_left=0xddc29df1,bottom_right=0xfff5a97f)"
	inactive_color=0xc02c2e34
	background_color=0x302c2e34
)

borders "${options[@]}"
