format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$cmd_duration\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$aws\
$docker_context\
$jobs\
$line_break\
$character"""

add_newline = true
palette = "dracula"

[username]
style_user = 'pink'
style_root = 'red'
format = '[$user]($style)'
disabled = false
show_always = true
aliases = { "lukas" = "way2abv" }

[hostname]
style = "bold purple"
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname]($style)'
trim_at = '.'
disabled = false
aliases = { "MacBookAir" = "mac " }

[directory]
style = "bold green"
format = '[$path ]($style)'
truncation_length = 4
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'bold pink'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_commit]
disabled = false
commit_hash_length = 6
tag_symbol = " "
only_detached = false
tag_disabled = false
format = '[$tag]($style) '
style = 'purple'

[git_status]
format = '(  $staged$modified$renamed$deleted$untracked)($style)'
untracked = '([$count untracked ](italic fg:bright-black))'
modified = '([$count modified ](italic fg:bright-black))'
staged = '([$count modified ](italic green))'
deleted = '([$count deleted ](italic green))'
renamed = '([$count renamed ](italic green))'

[fill]
symbol = ' '

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[golang]
style = 'blue'
symbol = ' '

[haskell]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[ruby]
style = 'blue'
symbol = ' '

[package]
symbol = '󰏗 '

[aws]
symbol = ' '
style = "bold orange"
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
style = 'fg:gray'
format = '[$duration]($style)'

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
